# Generated by Django 4.0.1 on 2022-03-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_TESTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=100)),
                ('test_instruction', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('files', models.FileField(max_length=250, upload_to='')),
                ('test_unique_id', models.CharField(max_length=12)),
                ('course_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.available_courses')),
            ],
        ),
    ]
