# Generated by Django 4.0.1 on 2022-03-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_tests',
            name='test_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
