# Generated by Django 4.0.1 on 2022-03-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_all_tests_test_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_tests',
            options={'ordering': ('test_unique_id',)},
        ),
        migrations.AddField(
            model_name='all_tests',
            name='test_questions',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='all_tests',
            name='files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='all_tests',
            name='test_data',
            field=models.TextField(default=None),
        ),
    ]
